// Mock data for preview without database setup

export const mockUser = {
  id: "user-1",
  email: "admin@acme.com",
  name: "Admin Usuario",
  role: "ADMIN" as const,
}

export const mockLocals = [
  {
    id: "local-1",
    name: "Sucursal Centro",
    tenantId: "tenant-1",
    channels: [
      {
        id: "channel-1",
        type: "INSTAGRAM" as const,
        displayName: "@acme_centro",
        status: "ACTIVE" as const,
        localId: "local-1",
      },
      {
        id: "channel-2",
        type: "WHATSAPP" as const,
        displayName: "+52 55 1234 5678",
        status: "ACTIVE" as const,
        localId: "local-1",
      },
    ],
  },
  {
    id: "local-2",
    name: "Sucursal Norte",
    tenantId: "tenant-1",
    channels: [
      {
        id: "channel-3",
        type: "FACEBOOK" as const,
        displayName: "ACME Norte",
        status: "ACTIVE" as const,
      },
    ],
  },
]

export const mockMembers = [
  {
    id: "member-1",
    userId: "user-1",
    tenantId: "tenant-1",
    role: "ADMIN" as const,
    user: {
      id: "user-1",
      name: "Admin Usuario",
      email: "admin@acme.com",
    },
  },
  {
    id: "member-2",
    userId: "user-2",
    tenantId: "tenant-1",
    role: "AGENT" as const,
    user: {
      id: "user-2",
      name: "María García",
      email: "maria@acme.com",
    },
  },
  {
    id: "member-3",
    userId: "user-3",
    tenantId: "tenant-1",
    role: "AGENT" as const,
    user: {
      id: "user-3",
      name: "Carlos López",
      email: "carlos@acme.com",
    },
  },
]

export const mockThreads = [
  {
    id: "thread-1",
    tenantId: "tenant-1",
    localId: "local-1",
    channelId: "channel-1",
    contactId: "contact-1",
    subject: "Consulta sobre productos",
    status: "OPEN" as const,
    priority: "MEDIUM" as const,
    assigneeId: "user-2",
    lastMessageAt: new Date("2025-01-15T10:30:00"),
    createdAt: new Date("2025-01-15T10:00:00"),
    channel: {
      id: "channel-1",
      type: "INSTAGRAM" as const,
      displayName: "@acme_centro",
      status: "ACTIVE" as const,
    },
    local: {
      id: "local-1",
      name: "Sucursal Centro",
    },
    assignee: {
      id: "user-2",
      name: "María García",
      email: "maria@acme.com",
    },
    contact: {
      id: "contact-1",
      handle: "@juanperez",
      name: "Juan Pérez",
      email: null,
      phone: null,
      avatarUrl: null,
    },
    messages: [
      {
        id: "msg-1",
        threadId: "thread-1",
        direction: "INBOUND" as const,
        content: "Hola, quisiera información sobre sus productos",
        sentAt: new Date("2025-01-15T10:30:00"),
      },
      {
        id: "msg-1-reply",
        threadId: "thread-1",
        direction: "OUTBOUND" as const,
        content: "¡Hola Juan! Con gusto te ayudo. ¿Qué tipo de productos te interesan?",
        sentAt: new Date("2025-01-15T10:32:00"),
        status: "DELIVERED" as const,
        attachments: [],
        author: {
          id: "user-2",
          name: "María García",
          email: "maria@acme.com",
        },
      },
    ],
  },
  {
    id: "thread-2",
    tenantId: "tenant-1",
    localId: "local-1",
    channelId: "channel-2",
    contactId: "contact-2",
    subject: "Problema con pedido #1234",
    status: "OPEN" as const,
    priority: "HIGH" as const,
    assigneeId: "user-3",
    lastMessageAt: new Date("2025-01-15T11:45:00"),
    createdAt: new Date("2025-01-15T09:00:00"),
    channel: {
      id: "channel-2",
      type: "WHATSAPP" as const,
      displayName: "+52 55 1234 5678",
      status: "ACTIVE" as const,
    },
    local: {
      id: "local-1",
      name: "Sucursal Centro",
    },
    assignee: {
      id: "user-3",
      name: "Carlos López",
      email: "carlos@acme.com",
    },
    contact: {
      id: "contact-2",
      handle: "+52 55 9876 5432",
      name: "Ana Martínez",
      email: "ana@example.com",
      phone: "+52 55 9876 5432",
      avatarUrl: null,
    },
    messages: [
      {
        id: "msg-2",
        threadId: "thread-2",
        direction: "INBOUND" as const,
        content: "Mi pedido #1234 no ha llegado y ya pasaron 5 días",
        sentAt: new Date("2025-01-15T11:45:00"),
      },
      {
        id: "msg-2-reply",
        threadId: "thread-2",
        direction: "OUTBOUND" as const,
        content: "Hola Ana, lamento mucho el inconveniente. Déjame revisar el estatus de tu pedido #1234 de inmediato.",
        sentAt: new Date("2025-01-15T11:47:00"),
        status: "DELIVERED" as const,
        attachments: [],
        author: {
          id: "user-3",
          name: "Carlos López",
          email: "carlos@acme.com",
        },
      },
    ],
  },
  {
    id: "thread-3",
    tenantId: "tenant-1",
    localId: "local-2",
    channelId: "channel-3",
    contactId: "contact-3",
    subject: "Horarios de atención",
    status: "PENDING" as const,
    priority: "LOW" as const,
    assigneeId: null,
    lastMessageAt: new Date("2025-01-15T08:15:00"),
    createdAt: new Date("2025-01-15T08:15:00"),
    channel: {
      id: "channel-3",
      type: "FACEBOOK" as const,
      displayName: "ACME Norte",
      status: "ACTIVE" as const,
    },
    local: {
      id: "local-2",
      name: "Sucursal Norte",
    },
    assignee: null,
    contact: {
      id: "contact-3",
      handle: "laura.rodriguez",
      name: "Laura Rodríguez",
      email: null,
      phone: null,
      avatarUrl: null,
    },
    messages: [
      {
        id: "msg-3",
        threadId: "thread-3",
        direction: "INBOUND" as const,
        content: "¿Cuál es su horario de atención los fines de semana?",
        sentAt: new Date("2025-01-15T08:15:00"),
      },
    ],
  },
  {
    id: "thread-4",
    tenantId: "tenant-1",
    localId: "local-1",
    channelId: "channel-1",
    contactId: "contact-4",
    subject: "Solicitud de cotización",
    status: "CLOSED" as const,
    priority: "MEDIUM" as const,
    assigneeId: "user-2",
    lastMessageAt: new Date("2025-01-14T16:20:00"),
    createdAt: new Date("2025-01-14T14:00:00"),
    channel: {
      id: "channel-1",
      type: "INSTAGRAM" as const,
      displayName: "@acme_centro",
      status: "ACTIVE" as const,
    },
    local: {
      id: "local-1",
      name: "Sucursal Centro",
    },
    assignee: {
      id: "user-2",
      name: "María García",
      email: "maria@acme.com",
    },
    contact: {
      id: "contact-4",
      handle: "@empresabc",
      name: "Empresa ABC",
      email: "contacto@empresaabc.com",
      phone: null,
      avatarUrl: null,
    },
    messages: [
      {
        id: "msg-4",
        threadId: "thread-4",
        direction: "INBOUND" as const,
        content: "Necesito cotización para 100 unidades",
        sentAt: new Date("2025-01-14T16:20:00"),
      },
      {
        id: "msg-4-reply",
        threadId: "thread-4",
        direction: "OUTBOUND" as const,
        content:
          "Perfecto, te envío la cotización por correo en las próximas horas. ¿Necesitas alguna especificación particular?",
        sentAt: new Date("2025-01-14T16:25:00"),
        status: "DELIVERED" as const,
        attachments: [],
        author: {
          id: "user-2",
          name: "María García",
          email: "maria@acme.com",
        },
      },
    ],
  },
  {
    id: "thread-5",
    tenantId: "tenant-1",
    localId: "local-1",
    channelId: "channel-2",
    contactId: "contact-5",
    subject: "Pregunta sobre garantía",
    status: "OPEN" as const,
    priority: "MEDIUM" as const,
    assigneeId: "user-1",
    lastMessageAt: new Date("2025-01-15T12:00:00"),
    createdAt: new Date("2025-01-15T11:30:00"),
    channel: {
      id: "channel-2",
      type: "WHATSAPP" as const,
      displayName: "+52 55 1234 5678",
      status: "ACTIVE" as const,
    },
    local: {
      id: "local-1",
      name: "Sucursal Centro",
    },
    assignee: {
      id: "user-1",
      name: "Admin Usuario",
      email: "admin@acme.com",
    },
    contact: {
      id: "contact-5",
      handle: "+52 55 1111 2222",
      name: "Roberto Sánchez",
      email: null,
      phone: "+52 55 1111 2222",
      avatarUrl: null,
    },
    messages: [
      {
        id: "msg-5",
        threadId: "thread-5",
        direction: "INBOUND" as const,
        content: "¿Cuánto tiempo de garantía tienen los productos?",
        sentAt: new Date("2025-01-15T12:00:00"),
      },
    ],
  },
]

export const mockAnalytics = {
  totalThreads: 156,
  openThreads: 42,
  closedThreads: 98,
  avgResponseTime: 12.5,
  channelData: [
    { name: "Instagram", value: 65 },
    { name: "WhatsApp", value: 52 },
    { name: "Facebook", value: 28 },
    { name: "TikTok", value: 11 },
  ],
  agentData: [
    { name: "María García", value: 48 },
    { name: "Carlos López", value: 42 },
    { name: "Admin Usuario", value: 35 },
    { name: "Sin asignar", value: 31 },
  ],
  messageVolume: 1247,
}

export const mockContacts = [
  {
    id: "contact-1",
    tenantId: "tenant-1",
    platform: "INSTAGRAM",
    handle: "@juanperez",
    name: "Juan Pérez",
    email: null,
    phone: null,
    avatarUrl: null,
    notes: "Cliente frecuente, interesado en productos premium",
    createdAt: new Date("2025-01-10T10:00:00"),
    threads: [{ id: "thread-1" }],
  },
  {
    id: "contact-2",
    tenantId: "tenant-1",
    platform: "WHATSAPP",
    handle: "+52 55 9876 5432",
    name: "Ana Martínez",
    email: "ana@example.com",
    phone: "+52 55 9876 5432",
    avatarUrl: null,
    notes: "Requiere seguimiento especial por problema con pedido",
    createdAt: new Date("2025-01-12T09:00:00"),
    threads: [{ id: "thread-2" }],
  },
  {
    id: "contact-3",
    tenantId: "tenant-1",
    platform: "FACEBOOK",
    handle: "laura.rodriguez",
    name: "Laura Rodríguez",
    email: null,
    phone: null,
    avatarUrl: null,
    notes: null,
    createdAt: new Date("2025-01-15T08:00:00"),
    threads: [{ id: "thread-3" }],
  },
  {
    id: "contact-4",
    tenantId: "tenant-1",
    platform: "INSTAGRAM",
    handle: "@empresabc",
    name: "Empresa ABC",
    email: "contacto@empresaabc.com",
    phone: "+52 55 3333 4444",
    avatarUrl: null,
    notes: "Cliente corporativo - solicitudes de cotización frecuentes",
    createdAt: new Date("2025-01-08T14:00:00"),
    threads: [{ id: "thread-4" }],
  },
  {
    id: "contact-5",
    tenantId: "tenant-1",
    platform: "WHATSAPP",
    handle: "+52 55 1111 2222",
    name: "Roberto Sánchez",
    email: null,
    phone: "+52 55 1111 2222",
    avatarUrl: null,
    notes: null,
    createdAt: new Date("2025-01-15T11:00:00"),
    threads: [{ id: "thread-5" }],
  },
]

export const mockMessages = [
  {
    id: "msg-1",
    threadId: "thread-1",
    direction: "INBOUND",
    body: "Hola, quisiera información sobre sus productos",
    sentAt: new Date("2025-01-15T10:30:00"),
    status: "DELIVERED",
    attachments: [],
    contact: {
      name: "Juan Pérez",
      handle: "@juanperez",
    },
  },
  {
    id: "msg-1-reply",
    threadId: "thread-1",
    direction: "OUTBOUND",
    body: "¡Hola Juan! Con gusto te ayudo. ¿Qué tipo de productos te interesan?",
    sentAt: new Date("2025-01-15T10:32:00"),
    status: "DELIVERED",
    attachments: [],
    author: {
      name: "María García",
      email: "maria@acme.com",
    },
  },
  {
    id: "msg-2",
    threadId: "thread-2",
    direction: "INBOUND",
    body: "Mi pedido #1234 no ha llegado y ya pasaron 5 días",
    sentAt: new Date("2025-01-15T11:45:00"),
    status: "DELIVERED",
    attachments: [],
    contact: {
      name: "Ana Martínez",
      handle: "+52 55 9876 5432",
    },
  },
  {
    id: "msg-2-reply",
    threadId: "thread-2",
    direction: "OUTBOUND",
    body: "Hola Ana, lamento mucho el inconveniente. Déjame revisar el estatus de tu pedido #1234 de inmediato.",
    sentAt: new Date("2025-01-15T11:47:00"),
    status: "DELIVERED",
    attachments: [],
    author: {
      name: "Carlos López",
      email: "carlos@acme.com",
    },
  },
  {
    id: "msg-3",
    threadId: "thread-3",
    direction: "INBOUND",
    body: "¿Cuál es su horario de atención los fines de semana?",
    sentAt: new Date("2025-01-15T08:15:00"),
    status: "DELIVERED",
    attachments: [],
    contact: {
      name: "Laura Rodríguez",
      handle: "laura.rodriguez",
    },
  },
  {
    id: "msg-4",
    threadId: "thread-4",
    direction: "INBOUND",
    body: "Necesito cotización para 100 unidades",
    sentAt: new Date("2025-01-14T16:20:00"),
    status: "DELIVERED",
    attachments: [],
    contact: {
      name: "Empresa ABC",
      handle: "@empresabc",
    },
  },
  {
    id: "msg-4-reply",
    threadId: "thread-4",
    direction: "OUTBOUND",
    body: "Perfecto, te envío la cotización por correo en las próximas horas. ¿Necesitas alguna especificación particular?",
    sentAt: new Date("2025-01-14T16:25:00"),
    status: "DELIVERED",
    attachments: [],
    author: {
      name: "María García",
      email: "maria@acme.com",
    },
  },
  {
    id: "msg-5",
    threadId: "thread-5",
    direction: "INBOUND",
    body: "¿Cuánto tiempo de garantía tienen los productos?",
    sentAt: new Date("2025-01-15T12:00:00"),
    status: "DELIVERED",
    attachments: [],
    contact: {
      name: "Roberto Sánchez",
      handle: "+52 55 1111 2222",
    },
  },
]

export const mockLocalsWithCount = [
  {
    id: "local-1",
    name: "Sucursal Centro",
    address: "Av. Reforma 123, CDMX",
    tenantId: "tenant-1",
    channels: [
      {
        id: "channel-1",
        type: "INSTAGRAM",
        displayName: "@acme_centro",
        status: "ACTIVE",
      },
      {
        id: "channel-2",
        type: "WHATSAPP",
        displayName: "+52 55 1234 5678",
        status: "ACTIVE",
      },
    ],
    _count: {
      threads: 87,
    },
  },
  {
    id: "local-2",
    name: "Sucursal Norte",
    address: "Blvd. Norte 456, Monterrey",
    tenantId: "tenant-1",
    channels: [
      {
        id: "channel-3",
        type: "FACEBOOK",
        displayName: "ACME Norte",
        status: "ACTIVE",
      },
      {
        id: "channel-4",
        type: "TIKTOK",
        displayName: "@acme_norte",
        status: "ACTIVE",
      },
    ],
    _count: {
      threads: 69,
    },
  },
]

export const mockSLAs = [
  {
    id: "sla-1",
    tenantId: "tenant-1",
    name: "SLA Estándar",
    firstResponseMinutes: 30,
    resolutionMinutes: 240,
    isActive: true,
    createdAt: new Date("2025-01-01T00:00:00"),
    updatedAt: new Date("2025-01-01T00:00:00"),
  },
  {
    id: "sla-2",
    tenantId: "tenant-1",
    name: "SLA Premium",
    firstResponseMinutes: 15,
    resolutionMinutes: 120,
    isActive: false,
    createdAt: new Date("2025-01-01T00:00:00"),
    updatedAt: new Date("2025-01-01T00:00:00"),
  },
]

export function getMockMessagesByThreadId(threadId: string) {
  return mockMessages.filter((msg) => msg.threadId === threadId)
}
